### ISSUE TITLE
Preprocessed path and vocabulary path issue

### ISSUE THREAD

**Issue by varadbhogayata** [Cyanogenoid/pytorch-vqa#12]
I am getting error when running preprocess-images.py file because I don't have resnet-14x14.h5 and vocab.json files. How can I get these files?

Thanks in advance!!

**Comment by Cyanogenoid** [comment]
Just follow the instructions at https://github.com/Cyanogenoid/pytorch-vqa#running-the-model .

**Comment by songzijiang** [comment]
I didn`t find resnet-14x14.h5. The pre-trained model is .pth named resnet152-caffe.pth. Do you know how to get resnet-14x14.h5. Thank you.

**Comment by Haochen-Luo** [comment]
> I didn`t find resnet-14x14.h5. The pre-trained model is .pth named resnet152-caffe.pth. Do you know how to get resnet-14x14.h5. Thank you.

I solved this issue by adding 'w' parameter in line 58 of  `preprocess-images.py`. The revised one is 
![image](https://user-images.githubusercontent.com/46443218/119636880-fc7f0580-be0c-11eb-8b68-862412e965d6.png)
