### ISSUE TITLE
ssd create issue

### ISSUE THREAD

**Issue by JuHyung-Son** [Cyanogenoid/pytorch-vqa#14]
I have this issue:
OSError: Unable to create file (unable to open file: name = '/ssd/resnet-14x14.h5', errno = 2, error message = 'No such file or directory', flags = 15, o_flags = c2)

**Comment by Cyanogenoid** [comment]
Read the instructions more carefully: `Set the paths to your downloaded questions, answers, and MS COCO images in config.py.` I've updated the config now to save it to the local directory by default, so this shouldn't happen anymore.
