### ISSUE TITLE
AttributeError: module ‘torchvision.transforms’ has no attribute ‘Scale’

### ISSUE THREAD

**Issue by gipster** [Cyanogenoid/pytorch-vqa#24]
Hi 

I got this error running your code

`AttributeError: module ‘torchvision.transforms’ has no attribute ‘Scale’`

I'm using torchvision 0.12, and `Scale` was [deprecated](https://discuss.pytorch.org/t/attributeerror-module-torchvision-transforms-has-no-attribute-scale/146687) in favour of `Resize` 

Modifying [this line](https://github.com/Cyanogenoid/pytorch-vqa/blob/master/utils.py#L131) of code fixes it.

**Comment by Cyanogenoid** [comment]
If you make a pull request with that change, I'll merge it.

**Comment by gipster** [comment]
Hey. Sorry for the delay. Just opened a PR for that.

**Comment by Cyanogenoid** [comment]
Thanks for the PR!
