### ISSUE TITLE
maximum q len

### ISSUE THREAD

**Issue by elbaro** [Cyanogenoid/pytorch-vqa#4]
The paper said questions are capped at 15 words, but I can't find any mention of 15 in the code.

**Comment by Cyanogenoid** [comment]
This code uses per-example unrolling, which is indeed different from what the paper does. If you want to change it to cap at 15 words, you can modify [_encode_question()](https://github.com/Cyanogenoid/pytorch-vqa/blob/master/data.py#L110) to only use the first 15 tokens and always return a length of 15.

**Comment by elbaro** [comment]
Just wanted to confirm. Thanks!
