### ISSUE TITLE
Working with abstract scenes VQA v1

### ISSUE THREAD

**Issue by varunnrao** [Cyanogenoid/pytorch-vqa#9]
In place of MSCOCO images, would the code work as is with the abstract scene images? We will place the images in the same folders as mentioned in the config.py folder.

**Comment by Cyanogenoid** [comment]
I don't know whatf filename format the abstract VQA images, but as long as you can give a unique ID to each image, it should be fine. You might have to change how the id is extracted from a filename here: https://github.com/Cyanogenoid/pytorch-vqa/blob/master/data.py#L224
